name: Build and deploy Node.js app to Azure Web App - faceapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build . -t faceapp:latest

      # List Docker images to verify build
      - name: List Docker images
        run: |
          docker images

      # Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io

      # Tag and Push Docker image to ACR
      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag faceapp:latest ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/faceapp:latest
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/faceapp:latest

      # List images in ACR to verify push
      - name: List images in Azure Container Registry
        run: |
          az acr repository list --name ${{ secrets.AZURE_REGISTRY_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BAAC538F7B1546248D94A1B7C35FFA0B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6ABDDA8ADD734522AFD89F7BC11F47EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_550C2BE7B0BB4AB693844F8D267DB225 }}

      # Deploy to Azure Web App using Docker
      - name: Deploy to Azure Web App using Docker
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'faceapp'
          slot-name: 'Production'  # Optional, set to 'Production' or your specified slot
          images: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/faceapp:latest
